# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626e8d4558d4ec0bd68b9c9bb54f18b1755b1ae97fa24d3dcb921d78d5b8f656c8163eda16c74141e8d358b63d3f4ea90d38bfbb60c2f7ae51f5e825f608fd25

test:
  secret_key_base: 235f10a33944599b6b302ef2e229092dc6311f692101e1fd32997e77c4672c1dc670c518928e3eedba7041c51233a43e3d5aea55d7c6ebb91f1fa19b2a9480e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
